import { z } from "zod";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";

export function registerCompareModelSnapshotTool(server: McpServer) {
  server.tool(
    "compare_model_snapshot",
    "Compare two model snapshots generated by create_model_snapshot to find Added, Removed, and Modified elements. No Revit connection needed.",
    {
      snapshot1: z.any().describe("The older snapshot JSON object. Must have an 'elements' property."),
      snapshot2: z.any().describe("The newer snapshot JSON object. Must have an 'elements' property.")
    },
    async (args, extra) => {
      try {
        const s1 = args.snapshot1?.elements || args.snapshot1;
        const s2 = args.snapshot2?.elements || args.snapshot2;

        if (!s1 || !s2 || typeof s1 !== 'object' || typeof s2 !== 'object') {
          throw new Error("Invalid snapshots provided. Expected objects containing elements.");
        }

        const added = [];
        const removed = [];
        const modified = [];

        const keys1 = new Set(Object.keys(s1));
        const keys2 = new Set(Object.keys(s2));

        for (const k of keys2) {
          if (!keys1.has(k)) {
            added.push({ id: k, ...s2[k] });
          } else {
            // Compare hash
            if (s1[k].hash !== s2[k].hash) {
              modified.push({ id: k, oldHash: s1[k].hash, newHash: s2[k].hash, info: s2[k] });
            }
          }
        }

        for (const k of keys1) {
          if (!keys2.has(k)) {
            removed.push({ id: k, ...s1[k] });
          }
        }

        const result = {
          addedCount: added.length,
          removedCount: removed.length,
          modifiedCount: modified.length,
          added,
          removed,
          modified
        };

        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }] };
      } catch (error) {
        return { content: [{ type: "text", text: `Compare snapshot failed: ${error instanceof Error ? error.message : String(error)}` }] };
      }
    }
  );
}
